controller_list:
  - name: fake_wp_manipulator_3rx_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
initial:  # Define initial robot poses.
#  - group: wp_manipulator_3rx_arm
#    pose: home
