# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
joint1:
  ID: 2
  Return_Delay_Time: 0
  Min_Position_Limit: 800
  Max_Position_Limit: 2000
joint2:
  ID: 3
  Return_Delay_Time: 0
  Min_Position_Limit: 1300
  Max_Position_Limit: 2700
joint3:
  ID: 4
  Return_Delay_Time: 0
  Min_Position_Limit: 900
  Max_Position_Limit: 3100
joint4:
  ID: 5
  Return_Delay_Time: 0
  Min_Position_Limit: 900
  Max_Position_Limit: 3000