# Position Controllers ---------------------------------------
joint1_position_controller:
  command_topic: joint1_velocity_controller/command
  joint: joint1
  pid: {p: 22.0, i: 15.0, d: 0.0, high_limit: 6, low_limit: -6}
joint2_position_controller:
  command_topic: joint2_velocity_controller/command
  joint: joint2
  pid: {p: 16.0, i: 10.0, d: 0.0, high_limit: 6, low_limit: -6}
joint3_position_controller:
  command_topic: joint3_velocity_controller/command
  joint: joint3
  pid: {p: 25.0, i: 5.0, d: 0.0, high_limit: 6, low_limit: -6}