topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False

  constraints:

    velocity:
      x: 0.25
      y: 0.25
      z: 0.25
      yaw: 0.25
      roll: 0.25
      pitch: 0.25

    acceleration:
      x: 0.25
      y: 0.25
      z: 0.25
      yaw: 0.2
      roll: 0.2
      pitch: 0.2
