controller_list:
  - name: fake_asap_manipulator_4r_reversed_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: asap_manipulator_4r_reversed_arm
    pose: home